# Generated by Django 5.2.5 on 2025-08-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChicksApp', '0002_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('farmer', 'farmer'), ('sales_agent', 'sales_agent'), ('manager', 'manager')], default='manager', max_length=20),
        ),
    ]
