# Generated by Django 5.2.5 on 2025-08-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChicksApp', '0003_alter_customer_age_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chickrequest',
            name='chick_request_id',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='farmer_id',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='feedallocation',
            name='feed_request_id',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
