# Generated by Django 5.2.5 on 2025-08-11 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChicksApp', '0004_alter_chickrequest_chick_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedallocation',
            name='feed_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ChicksApp.feedstock'),
        ),
        migrations.AddField(
            model_name='feedallocation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
