# Generated by Django 5.2.5 on 2025-08-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChicksApp', '0005_feedallocation_feed_stock_feedallocation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickrequest',
            name='feed_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='feedallocation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
