# Generated by Django 5.2.5 on 2025-08-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChicksApp', '0006_chickrequest_feed_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
