# Generated by Django 5.2.5 on 2025-08-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChicksApp', '0007_delete_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedallocation',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
