# Generated by Django 5.2.5 on 2025-08-19 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChicksApp', '0008_feedallocation_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sales_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_farmers', to=settings.AUTH_USER_MODEL),
        ),
    ]
