# Generated by Django 5.2.5 on 2025-08-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChicksApp', '0009_customer_sales_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='farmer_id',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
